# Flavor of configuration:
# - client: httptunnel + haproxy
# - server: ingress + httptunnel + haproxy
side: client

client:
  service:
    name: rabbitmq
    port: 5672

server:
  ingress:
    ingressClassName: ""
    annotations: {}
    hostname: rabbitmq.local
    path: /
    tls: true
  service:
    name: rabbitmq
    port: 5672

haproxy:
  enabled: true

